### PR TITLE
Restore add(Promise) and addAll(Promise...) methods to PromiseCombiner (fixes #6283)

### LINKED ISSUE #6283: 4.1.7 PromiseCombiner not binary-compatible with previous version?
After upgrading to netty 4.1.7 from 4.1.6, we're getting:
```
java.lang.NoSuchMethodError: io.netty.util.concurrent.PromiseCombiner.addAll([Lio/netty/util/concurrent/Promise;)V
	at com.relayrides.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:815)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:832)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at com.relayrides.pushy.apns.ApnsClient.sendNotification(ApnsClient.java:900)
	at com.relayrides.pushy.apns.ApnsClient.sendNotification(ApnsClient.java:857)
```
Probably related to https://github.com/netty/netty/commit/7c630feefc62b739afea123547165b9efb4281c0
 @jchambers ?

### PR DESCRIPTION
**Pull request by jchambers**
## Motivation

A testing goof in 7c630fe introduced a binary incompatibility when the old Promise-specific `add` and `addAll` methods in `PromiseCombiner` were generalized to accept `Futures`.

## Modification

- Restore (but mark as `@Deprecated`) old `PromiseCombiner` methods.
- Fixed a couple minor documentation typos because sure why not.

## Result

Fixes #6283; `PromiseCombiner` is binary-compatible with previous versions of Netty.

----

Sorry for the trouble here! @normanmaurer totally called this one, but I managed to convince myself through (incorrect) testing that it wasn't an issue.

### CODE REVIEW

**Comment by normanmaurer** [comment]
Cherry-picked into 4.1 (94cb389c04bd084f698345aac4cb70b02e5da086)

@jchambers thanks a lot!
