### ISSUE TITLE
4.1.7 PromiseCombiner not binary-compatible with previous version?

### ISSUE THREAD

**Issue by flozano** [netty/netty#6283]
After upgrading to netty 4.1.7 from 4.1.6, we're getting:
```
java.lang.NoSuchMethodError: io.netty.util.concurrent.PromiseCombiner.addAll([Lio/netty/util/concurrent/Promise;)V
	at com.relayrides.pushy.apns.ApnsClientHandler.write(ApnsClientHandler.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:815)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:832)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at com.relayrides.pushy.apns.ApnsClient.sendNotification(ApnsClient.java:900)
	at com.relayrides.pushy.apns.ApnsClient.sendNotification(ApnsClient.java:857)
```
Probably related to https://github.com/netty/netty/commit/7c630feefc62b739afea123547165b9efb4281c0
 @jchambers ?

**Comment by normanmaurer** [comment]
@flozano @jchambers yes seems so... Could you open a PR which adds back the old methods as well ? and delegate to the new ones ? this should fix it.

**Comment by jchambers** [comment]
Ugh… I'm really sorry. Not sure why this was okay in testing for me. I can open a pull request on Saturday if somebody doesn't beat me to the punch.

**Comment by jchambers** [comment]
This should be fixed in #6292. Sorry for the trouble!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6292
