### ISSUE TITLE
Starting from netty-transport-native-kqueue 4.1.80.Final, KQueue is unavailable on Apple Silicon

### ISSUE THREAD

**Issue by lepistone** [netty/netty#13047]
### Expected behavior
`KQueue.isAvailable()` is true

### Actual behavior
`KQueue.isAvailable()` is false starting from 4.1.80.Final. It was true with 4.1.79.Final.
`java.lang.NoSuchMethodError: Method io.netty.channel.unix.Socket.send(ILjava/nio/ByteBuffer;II)I not found`

### Minimal yet complete reproducer code (or URL to code)
System.out.println(KQueue.isAvailable());
System.out.println(KQueue.unavailabilityCause());

### Netty version
4.1.80.Final. This worked fine on 4.1.79.Final.

### JVM version (e.g. `java -version`)
Corretto-19.0.1.10.1

### OS version (e.g. `uname -a`)
Darwin Kernel Version 22.1.0
MacOS Ventura 13.0.1 (22A400)
Apple M1 Max

**Comment by lepistone** [comment]
By looking at the changelog, this might be caused by #12679.

**Comment by chrisvest** [comment]
You have a mix of Netty versions on your classpath. Specifically, your `*-unix-common` version does not match your `*-kqueue` versions.

**Comment by lepistone** [comment]
You are right! Thanks for the quick answer and sorry for the noise.
