### ISSUE TITLE
libnetty_resolver_dns_native_macos_x86_64 crash when upgrading from 4.1.87 to 4.1.88

### ISSUE THREAD

**Issue by slandelle** [netty/netty#13215]
OS 11.4
Darwin Kernel Version 20.5.0

```
dyld: lazy symbol binding failed: Symbol not found: _netty_jni_util_JNI_OnLoad
  Referenced from: /private/var/folders/9y/1ld4xhrs4q9g3dt33dt9t53c0000gn/T/libnetty_resolver_dns_native_macos_x86_642861775474910762688.dylib
  Expected in: flat namespace

dyld: Symbol not found: _netty_jni_util_JNI_OnLoad
  Referenced from: /private/var/folders/9y/1ld4xhrs4q9g3dt33dt9t53c0000gn/T/libnetty_resolver_dns_native_macos_x86_642861775474910762688.dylib
  Expected in: flat namespace
```

**Comment by slandelle** [comment]
Ha ha, duplicate of #13214
