### PR TITLE
Make /etc/resolv.conf reading more robust

### LINKED ISSUE #13949: DefaultDnsServerAddressStreamProvider fails when /etc/resolv.conf is not present on ZOS
### Expected behavior
`DefaultDnsServerAddressStreamProvider` should fallback to the existing lookup if `/etc/resolv.conf` is not present

### Actual behavior
`IllegalStateException` that finally leads to a `NoClassDefFoundError` when `DnsServerAddresses.defaultAddressList()` is called on ZOS.

### Steps to reproduce
rename `/etc/resolv.conf` and call e.g. `DnsServerAddresses.defaultAddressList()`

### Netty version
Issue was introduced with https://github.com/netty/netty/pull/13884, so `4.1.108.Final`

### JVM version (e.g. `java -version`)
```
java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 8.0.8.15 - pmz3180sr8fp15-20231030_01(SR8 FP15))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390-31-Bit 20230908_57744 (JIT enabled, AOT enabled)
OpenJ9  - ec90c19
OMR   - 8b64d40
IBM   - 696e9df)
JCL - 20231012_01 based on Oracle jdk8u391-b13
```

### OS version (e.g. `uname -a`)
```
OS/390 TVT6016 28.00 04 2964
```

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
It is possible that /etc/resolv.conf is missing or cannot be read, in which case `ResolvConf.system()` will throw an exception. We need to handle that exception in `DefaultDnsServerAddressStreamProvider`, since exceptions thrown from a static initializer can become `NoClassDefFoundError`.

Modification:
Catch the exception that `ResolvConf.system()` might throw, an fall back to JNDI in that case.

Result:
No more `NoClassDefFoundError` being thrown when `/etc/resolv.conf` cannot be read for any reason.

Fixes #13949

### CODE REVIEW

**Comment by chrisvest** [comment]
FYI @snazy

**Review by snazy — APPROVED** [review]
