### ISSUE TITLE
dyld: Symbol not found: _netty_jni_util_JNI_OnLoad

### ISSUE THREAD

**Issue by violetagg** [netty/netty#13728]
Netty 4.1.103.Final fails with the error below when on Mac OS Intel

```
dyld: Symbol not found: _netty_jni_util_JNI_OnLoad
  Referenced from: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/libnetty_resolver_dns_native_macos_x86_642849015487497714394.dylib
  Expected in: flat namespace
```

Reactor Netty build with Netty 4.1.103.Final
https://github.com/reactor/reactor-netty/actions/runs/7195479140

### Netty version
4.1.103.Final

### JVM version (e.g. `java -version`)
java 8

### OS version (e.g. `uname -a`)
Mac OS

**Comment by hnljp** [comment]
I can also confirm this with java 21 on macOS.
Everything is working fine with 4.1.102.Final, but with 4.1.103.Final it is failing with "dyld[15642]: missing symbol called".

**Comment by hnljp** [comment]
> @hnljp is this on intel ?

Yes

**Comment by NilsRenaud** [comment]
Not sure it's 100% related, but when I set `DYLD_PRINT_LIBRARIES=true`, then `dyld` fails on:
```
dyld[9901]: <GARBAGE> /private/var/folders/8x/GARBAGE/T/libnetty_resolver_dns_native_macos_x86_646312351102592708593.dylib
dyld[9901]: missing symbol called
```

And when I inspect this file I can see: `/Users/norman/Documents/workspace/netty/resolver-dns-native-macos/target/native-build/target/lib/libnetty_resolver_dns_native_macos_x86_64-4.1.103.Final.jnilib`

So I guess this is a dev path hard written.

**Comment by normanmaurer** [comment]
A new release was done which should fix this. The problem was introduce because of some error while cross-compile

**Comment by violetagg** [comment]
I can confirm that I do not see this issue anymore with 4.1.104.Final. Thanks a lot!
