### ISSUE TITLE
`dyld: Symbol not found: _netty_jni_util_JNI_OnLoad` when upgrading from 4.1.87.Final to 4.1.88.Final

### ISSUE THREAD

**Issue by violetagg** [netty/netty#13214]
### Expected behavior
Reactor Netty CI to pass with Netty 4.1.88.Final

### Actual behavior
Reactor Netty CI fails with Netty 4.1.88.Final

```
dyld: lazy symbol binding failed: Symbol not found: _netty_jni_util_JNI_OnLoad

  Referenced from: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/libnetty_resolver_dns_native_macos_x86_643041317632771730980.dylib
  Expected in: flat namespace
```

### Minimal yet complete reproducer code (or URL to code)
Reactor Netty CI
https://github.com/reactor/reactor-netty/actions/runs/4161178857/jobs/7199562183

### Netty version
4.1.88.Final

### JVM version (e.g. `java -version`)
Distribution: temurin
Version: 8.0.362+9

### OS version (e.g. `uname -a`)
macOS 11.7.3

**Comment by normanmaurer** [comment]
I think there was something wrong when doing the release via m1. Will fix it with a followup release

**Comment by violetagg** [comment]
@normanmaurer Thanks

**Comment by slandelle** [comment]
@normanmaurer Thanks a lot! I confirm that the new release works.
